# Generated by Django 3.0 on 2020-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donations',
            fields=[
                ('donations_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('weight', models.IntegerField()),
                ('email', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=50)),
                ('postalcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('items_id', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.CharField(max_length=200)),
                ('itemPrice', models.IntegerField()),
                ('itemDiscounnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('secQue', models.CharField(max_length=30)),
                ('mobile', models.CharField(default='', max_length=30)),
                ('membership_type', models.CharField(default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('membership_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('typ', models.CharField(max_length=20)),
            ],
        ),
    ]
