# Generated by Django 3.0 on 2020-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemImage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donations',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
