# Generated by Django 3.0 on 2020-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20200829_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='ans',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='secQue',
            field=models.CharField(default='', max_length=30),
        ),
    ]
